### ISSUE TITLE
Broken version of dup

### ISSUE THREAD

**Issue by bnolan** [mikolalysenko/greedy-mesher#5]
Most fun debugging ever. The bump of version changed the version of typed-array, which is broken (dup is no longer a function but a dictionary).

**Comment by mikolalysenko** [comment]
Super weird and sorry about this.  I'm going to try fixing it

**Comment by mikolalysenko** [comment]
Ok, I just tried pushing a new version.  It runs all the tests locally on my machine with no problem.  Can you try installing greedy-mesher@1.0.3 and see if that works?  Also a minimal broken example would help solve the problem.

**Comment by bnolan** [comment]
It's working again now, sorry for the grumpy message. :)
